server:
  port: 9964
  tomcat:
    max-threads: 1000  # 处理请求任务的最大线程数
    min-spare-threads: 10 # 处理请求任务的最小线程数
    max-connections: 1000  # 最多可以有多少个socket连接到tomcat上
    accept-count: 1000 # 当所有可能的请求处理线程都在使用时，传入连接请求的最大队列长度。
    accesslog:
      directory: 'logs' #创建日志文件的目录。可以绝对或相对于Tomcat基础目录。
      prefix: 'access_log' #日志文件名前缀。
      suffix: '.log' #日志文件名后缀。
      pattern: 'common' #访问日志的格式模式。
      buffered: true #是否缓冲输出，使其仅定期刷新。
      enabled: false #启用访问日志。
      file-date-format: '.yyyy-MM-dd' #要放在日志文件名中的日期格式。
      rename-on-rotate: false #是否延迟在文件名中包含日期戳，直到旋转时间---设置为false，即刻会生成带有日期的日志文件名字
      request-attributes-enabled: false #设置请求的IP地址，主机名，协议和端口的请求属性。
      rotate: true #是否启用访问日志轮换。
    additional-tld-skip-patterns: #逗号分隔的其他模式列表，这些模式匹配要忽略的TLD扫描的jar。
    background-processor-delay: 10s #backgroundProcess 方法调用之间的延迟。如果未指定持续时间后缀，则将使用秒。
    basedir: #Tomcat 基目录。如果未指定，则使用临时目录。
    internal-proxies: '"10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|" // 10/8
                      + "192\\.168\\.\\d{1,3}\\.\\d{1,3}|" // 192.168/16
                      + "169\\.254\\.\\d{1,3}\\.\\d{1,3}|" // 169.254/16
                      + "127\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|" // 127/8
                      + "172\\.1[6-9]{1}\\.\\d{1,3}\\.\\d{1,3}|" // 172.16/12
                      + "172\\.2[0-9]{1}\\.\\d{1,3}\\.\\d{1,3}|" + "172\\.3[0-1]{1}\\.\\d{1,3}\\.\\d{1,3}|" //
                      + "0:0:0:0:0:0:0:1|::1"'#正则表达式匹配要信任的代理。
    max-http-post-size: 2MB #HTTP 内容的最大大小。
    max-swallow-size: 2MB #要吞咽的请求正文的最大数量。
    port-header: 'X-Forwarded-Port' #用于覆盖原始端口值的HTTP头的名称。
    protocol-header:  #包含传入协议的头文件，通常命名为“X-Forwarded-Proto”。
    protocol-header-https-value: https #协议标头的值，指示传入请求是否使用SSL。
    redirect-context-root: true #是否应通过在路径中附加/来重定向对上下文根的请求。
    remote-ip-header:   #从中提取远程IP的HTTP头的名称。例如，`X-FORWARDED-FOR`。
    resource:
      allow-caching: true  #是否允许此Web应用程序使用静态资源缓存
      cache-ttl: #静态资源缓存的生存时间。
    uri-encoding: utf-8 #用于解码URI的字符编码。
    use-relative-redirects:  #通过调用sendRedirect生成的HTTP 1.1和更高版本的位置标头是使用相对还是绝对重定向。

# DATABASE CONFIG
spring:
  application:
    name: zzq-simple-framework-json-client

httpclient:
    pool:
      test:
        maxIdleConnections: 1
        maxRequests: 5
        maxRequestsPerHost: 5
        connectTimeout: 10
        readTimeout: 10
        writeTimeout: 10

