spring:
  rabbitmq:
    first:
      host: 127.0.0.1
      port: 5672
      username: zzq
      password: zzq
      virtual-host: first
    second:
      host: 127.0.0.1
      port: 5672
      username: zzq
      password: zzq
      virtual-host: second
server:
  port: 7878
